# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import csv
import datetime
from statsmodels.tsa.arima_model import ARIMA

C:\Users\Dell\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

# Importing Data

In [2]:
data = pd.read_csv('Temperature-20201216-1824.csv')

# Viewing and Describing data

In [3]:
data

,id,value,feed_id,created_at,lat,lon,ele
0,0EM0ZPCRSB836BPS73EQ2ENV5F,18.4,1518525,2020-12-16 18:08:43 UTC,NaN,NaN,NaN
1,0EM0ZPDCBGRK2QP8BVAFQJTJ1Z,18.4,1518525,2020-12-16 18:08:45 UTC,NaN,NaN,NaN
2,0EM0ZPE03WKDE89T45YKTZN35N,19.1,1518525,2020-12-16 18:08:47 UTC,NaN,NaN,NaN
3,0EM0ZPEKRW3HJZYZB0HGDPTDRY,18.5,1518525,2020-12-16 18:08:49 UTC,NaN,NaN,NaN
4,0EM0ZPF7D8YW3BXREVA041VS9F,18.4,1518525,2020-12-16 18:08:51 UTC,NaN,NaN,NaN
5,0EM0ZPFV8Z1TTN8CSV6A1M366X,18.5,1518525,2020-12-16 18:08:53 UTC,NaN,NaN,NaN
6,0EM0ZPGFD6N53MXJ8Z2PMRTABG,18.0,1518525,2020-12-16 18:08:55 UTC,NaN,NaN,NaN
7,0EM0ZPH2PD4HKW9346DAHKDCEF,18.5,1518525,2020-12-16 18:08:57 UTC,NaN,NaN,NaN
8,0EM0ZPJF7HA9YN2NRCEACWJJH5,18.5,1518525,2020-12-16 18:09:01 UTC,NaN,NaN,NaN
9,0EM0ZPJF879MF2EECKN436GCSQ,18.7,1518525,2020-12-16 18:09:01 UTC,NaN,NaN,NaN
10,0EM0ZPVN748F1SR3837GRB7B3M,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
11,0EM0ZPVN8348FR2R1RNRYDTT7N,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
12,0EM0ZPVNA630DR145NH5G5WGYD,18.5,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
13,0EM0ZPVNAAXJK2ZZQJPMK3HY6A,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
14,0EM0ZPVNABXRA70242FTDYH8FW,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
15,0EM0ZPVNAEN4S98B7EKNG5XGEF,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
16,0EM0ZPVNDNFAJ2W2PBKNK478ZN,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
17,0EM0ZPVNEW2JWEZPN097WNGGHR,18.6,1518525,2020-12-16 18:09:31 UTC,NaN,NaN,NaN
18,0EM0ZPVQRR290SBQ3BJATAVF06,18.6,1518525,2020-12-16 18:09:32 UTC,NaN,NaN,NaN
19,0EM0ZRDDFWHYMBPQXHZ2ZBHXAV,19.2,1518525,2020-12-16 18:12:14 UTC,NaN,NaN,NaN
20,0EM0ZRE10J5JM448QMSC9A406Z,19.1,1518525,2020-12-16 18:12:16 UTC,NaN,NaN,NaN
21,0EM0ZREMDPBPRQVZ5QND1NVJWK,19.2,1518525,2020-12-16 18:12:18 UTC,NaN,NaN,NaN
22,0EM0ZRF88H7QWS5WAFTSH2PS5Y,19.2,1518525,2020-12-16 18:12:20 UTC,NaN,NaN,NaN
23,0EM0ZRFVVZW9XMDYWMXYRKGG0B,19.3,1518525,2020-12-16 18:12:22 UTC,NaN,NaN,NaN
24,0EM0ZRGFGGWXRNPY9N5D8X0KH3,19.2,1518525,2020-12-16 18:12:24 UTC,NaN,NaN,NaN
25,0EM0ZRH386ZFC6YCBR3HAV8695,19.2,1518525,2020-12-16 18:12:26 UTC,NaN,NaN,NaN
26,0EM0ZRHQA219TMAW0BTSM4MYYP,19.2,1518525,2020-12-16 18:12:29 UTC,NaN,NaN,NaN
27,0EM0ZRJANFGQWPNPXT9FZSS2MZ,19.2,1518525,2020-12-16 18:12:31 UTC,NaN,NaN,NaN
28,0EM0ZRJYFFMGJMY4XF17XE40F4,19.2,1518525,2020-12-16 18:12:33 UTC,NaN,NaN,NaN
29,0EM0ZRKHYJ6GKE9V70QN4HYYPW,19.0,1518525,2020-12-16 18:12:35 UTC,NaN,NaN,NaN
30,0EM0ZRM5RKZRAA0C58PKY57TAY,19.8,1518525,2020-12-16 18:12:37 UTC,NaN,NaN,NaN
31,0EM0ZRMSDXSVFB87RAYK9DW47D,19.2,1518525,2020-12-16 18:12:39 UTC,NaN,NaN,NaN
32,0EM0ZRND2EX54BS0PAHK364TK0,19.3,1518525,2020-12-16 18:12:41 UTC,NaN,NaN,NaN
33,0EM0ZRPG9898P1S0VENF876FQ4,19.3,1518525,2020-12-16 18:12:44 UTC,NaN,NaN,NaN
34,0EM0ZTM2777SA8Z76H7EMY9C97,21.4,1518525,2020-12-16 18:16:06 UTC,NaN,NaN,NaN
35,0EM0ZV5ZBKQ7XFXAMTXE1C8SV1,20.6,1518525,2020-12-16 18:17:05 UTC,NaN,NaN,NaN
36,0EM0ZV7T8XNEPB3DPN90GMB2QY,20.5,1518525,2020-12-16 18:17:11 UTC,NaN,NaN,NaN

In [4]:
data.shape

(37, 7)

In [5]:
data.describe()

           value    feed_id  lat  lon  ele
count  37.000000       37.0  0.0  0.0  0.0
mean   19.010811  1518525.0  NaN  NaN  NaN
std     0.678144        0.0  NaN  NaN  NaN
min    18.000000  1518525.0  NaN  NaN  NaN
25%    18.600000  1518525.0  NaN  NaN  NaN
50%    19.000000  1518525.0  NaN  NaN  NaN
75%    19.200000  1518525.0  NaN  NaN  NaN
max    21.400000  1518525.0  NaN  NaN  NaN

In [6]:
temps = data['value']

# Defining a "temps" variable to feed the model

In [7]:
temps

0     18.4
1     18.4
2     19.1
3     18.5
4     18.4
5     18.5
6     18.0
7     18.5
8     18.5
9     18.7
10    18.6
11    18.6
12    18.5
13    18.6
14    18.6
15    18.6
16    18.6
17    18.6
18    18.6
19    19.2
20    19.1
21    19.2
22    19.2
23    19.3
24    19.2
25    19.2
26    19.2
27    19.2
28    19.2
29    19.0
30    19.8
31    19.2
32    19.3
33    19.3
34    21.4
35    20.6
36    20.5
Name: value, dtype: float64

# Using the arima model to get the predictions

In [8]:
model_arima=ARIMA(temps,(1,1,0))
model_arima_fit=model_arima.fit()
prediction_arima=model_arima_fit.forecast(10)[0]
prediction_arima

array([20.62424714, 20.65861244, 20.72900382, 20.78495537, 20.84669464,
       20.9061141 , 20.96646337, 21.02643996, 21.08656593, 21.14663202])

In [9]:
prediction = pd.DataFrame(prediction_arima)

# Predictions and Saving to new CSV file

In [10]:
prediction.to_csv('Predicted_Data.csv')
prediction

           0
0  20.624247
1  20.658612
2  20.729004
3  20.784955
4  20.846695
5  20.906114
6  20.966463
7  21.026440
8  21.086566
9  21.146632

# Saving the trained model with pickle

In [11]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(model_arima,f)

# Load trained model with pickle no need to train again

In [12]:
with open('model_pickle','rb') as f:
    df = pickle.load(f)